name: Docker CI

on: [push]

jobs:
  BuildImage:

    env:
      IMAGE: culater/sabnzbd
      TEST_TAG: culater/sabnzbd:test
      LATEST_TAG: culater/sabnzbd:latest
      PORT: "8080"
    runs-on: ubuntu-latest

    steps:

    - name: Generate Build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        release=$(curl -s https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
        echo "::set-output name=BUILD_ID::${branch}-${release}"


    # These are prerequisites for the docker build step

    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # - name: Login to DockerHub
    #   uses: docker/login-action@v2
    #   with:
    #       username: ${{ secrets.DOCKER_USER }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image to github registry
      uses: docker/build-push-action@v2
      with:
        push: true 
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }},${{ env.IMAGE }}:latest

    - name: Inspect
      run: |
        docker image inspect ${{ env.IMAGE }}:latest

  SimpleTest:

    - name: Test image
      run: |
        docker run -d -v templates:/config --rm ${{ env.TEST_TAG }}
        curl -s http://docker:$PORT/ | grep -i "sabnzbd"
