name: Docker CI

on: [push]

jobs:
  build-push:

    env:
      IMAGE: culater/sabnzbd
    runs-on: ubuntu-latest

    steps:

    - name: Generate Build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        release=$(curl -s https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
        echo "::set-output name=BUILD_ID::${branch}-${release}"


    # These are prerequisites for the docker build step
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and publish container image
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        context: .
        tags: ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
