name: Docker CI

on: [push]

env:
  RELEASE: curl -s https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to dockerhub registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Obtain sabnzbd version
      run: |
        RELEASE = $(curl -s https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
        echo "release is $RELEASE"
    - name: Docker build
      run: |
        docker build -t culater/sabnzbd:${{ RELEASE }}
